# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches:
      - main
      - early-adapter

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '19'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Creating the jar file
        run: ./gradlew jar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./releases/*.jar
          name: Downloadable Extension File
      - name: Delete older releases
        uses: irsdl/delete-older-releases@v0.2.1
        with:
          repo: irsdl/BurpSuiteSharpenerEx
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set release tag based on branch
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=release_tag::main_latest_build_by_github"
          else
            echo "::set-output name=release_tag::early_adapter_latest_build_by_github"
          fi
      - name: Release
        uses: irsdl/release-action@v1.12.0
        with:
          tag: ${{ steps.vars.outputs.release_tag }}
          body: "This jar file has been built by GitHub automatically.\nYou can view the latest version number in the [extension.properties](../../blob/main/src/main/resources/extension.properties) file."
          allowUpdates: true
          artifacts: "releases/*.jar"
